=== EmekaC/BlockMom/referral-schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "resourceType": {
            "type": "string",
            "default": ""
        },
        "id": {
            "type": "string",
            "default": ""
        },
        "text": {"$ref": "#/definitions/text_type"},
        "identifier": {"$ref": "#/definitions/identifier_type"},
        "active": {
            "type": "boolean",
            "default": false
        },
        "name": {"$ref": "#/definitions/name_type"},
        "telecom": {"$ref": "#/definitions/telecom_type"},
        "gender": {
            "type": "string",
            "default": ""
        },
        "birthDate": {
            "type": "string",
            "default": ""
        },
        "_birthDate": {"$ref": "#/definitions/_birthDate_type"},
        "deceasedBoolean": {
            "type": "boolean",
            "default": false
        },
        "address": {"$ref": "#/definitions/address_type"},
        "contained": {"$ref": "#/definitions/contained_type"},
        "activity": {"$ref": "#/definitions/activity_type"}
    },
    "definitions": {
        "text_type": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "default": ""
                },
                "div": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "coding_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "system": {
                        "type": "string",
                        "format": "uri",
                        "default": ""
                    },
                    "code": {
                        "type": "string",
                        "default": ""
                    }
                },
                "required": [
                    "system",
                    "code"
                ]
            }
        },
        "type_type": {
            "type": "object",
            "properties": {
                "coding": {"$ref": "#/definitions/coding_type"}
            }
        },
        "period_type": {
            "type": "object",
            "properties": {
                "start": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "assigner_type": {
            "type": "object",
            "properties": {
                "display": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "identifier_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "use": {
                        "type": "string",
                        "default": ""
                    },
                    "type": {"$ref": "#/definitions/type_type"},
                    "system": {
                        "type": "string",
                        "default": ""
                    },
                    "value": {
                        "type": "string",
                        "default": ""
                    },
                    "period": {"$ref": "#/definitions/period_type"},
                    "assigner": {"$ref": "#/definitions/assigner_type"}
                },
                "required": [
                    "period",
                    "system",
                    "use",
                    "assigner",
                    "type",
                    "value"
                ]
            }
        },
        "given_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "string",
                "default": ""
            }
        },
        "period2_type": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "name_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "use": {
                        "type": "string",
                        "default": ""
                    },
                    "family": {
                        "type": "string",
                        "default": ""
                    },
                    "given": {"$ref": "#/definitions/given_type"},
                    "period": {"$ref": "#/definitions/period2_type"}
                },
                "required": [
                    "given",
                    "use"
                ]
            }
        },
        "telecom_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "use": {
                        "type": "string",
                        "default": ""
                    },
                    "system": {
                        "type": "string",
                        "default": ""
                    },
                    "value": {
                        "type": "string",
                        "default": ""
                    },
                    "rank": {
                        "type": "integer",
                        "default": 0
                    },
                    "period": {"$ref": "#/definitions/period2_type"}
                },
                "required": ["use"]
            }
        },
        "extension_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "format": "uri",
                        "default": ""
                    },
                    "valueDateTime": {
                        "type": "string",
                        "format": "date-time",
                        "default": ""
                    }
                },
                "required": [
                    "valueDateTime",
                    "url"
                ]
            }
        },
        "_birthDate_type": {
            "type": "object",
            "properties": {
                "extension": {"$ref": "#/definitions/extension_type"}
            }
        },
        "address_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "use": {
                        "type": "string",
                        "default": ""
                    },
                    "type": {
                        "type": "string",
                        "default": ""
                    },
                    "text": {
                        "type": "string",
                        "default": ""
                    },
                    "line": {"$ref": "#/definitions/given_type"},
                    "city": {
                        "type": "string",
                        "default": ""
                    },
                    "district": {
                        "type": "string",
                        "default": ""
                    },
                    "state": {
                        "type": "string",
                        "default": ""
                    },
                    "postalCode": {
                        "type": "string",
                        "default": ""
                    },
                    "period": {"$ref": "#/definitions/period_type"}
                },
                "required": [
                    "period",
                    "city",
                    "use",
                    "line",
                    "district",
                    "postalCode",
                    "text",
                    "state",
                    "type"
                ]
            }
        },
        "code_type": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "default": ""
                },
                "value": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "subject_type": {
            "type": "object",
            "properties": {
                "reference": {
                    "type": "string",
                    "default": ""
                },
                "display": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "name2_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "family": {
                        "type": "string",
                        "default": ""
                    },
                    "given": {"$ref": "#/definitions/given_type"}
                },
                "required": [
                    "given",
                    "family"
                ]
            }
        },
        "contained_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "resourceType": {
                        "type": "string",
                        "default": ""
                    },
                    "id": {
                        "type": "string",
                        "default": ""
                    },
                    "clinicalStatus": {"$ref": "#/definitions/type_type"},
                    "verificationStatus": {"$ref": "#/definitions/type_type"},
                    "code": {"$ref": "#/definitions/code_type"},
                    "subject": {"$ref": "#/definitions/subject_type"},
                    "name": {"$ref": "#/definitions/name2_type"}
                },
                "required": [
                    "id",
                    "resourceType"
                ]
            }
        },
        "extension2_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "valueUri": {
                        "type": "string",
                        "format": "uri",
                        "default": ""
                    }
                },
                "required": ["valueUri"]
            }
        },
        "code2_type": {
            "type": "object",
            "properties": {
                "coding": {"$ref": "#/definitions/coding_type"},
                "text": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "boundsPeriod_type": {
            "type": "object",
            "properties": {
                "start": {
                    "type": "string",
                    "default": ""
                },
                "end": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "repeat_type": {
            "type": "object",
            "properties": {
                "boundsPeriod": {"$ref": "#/definitions/boundsPeriod_type"}
            }
        },
        "scheduledTiming_type": {
            "type": "object",
            "properties": {
                "repeat": {"$ref": "#/definitions/repeat_type"}
            }
        },
        "performer_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "reference": {
                        "type": "string",
                        "default": ""
                    },
                    "display": {
                        "type": "string",
                        "default": ""
                    }
                },
                "required": [
                    "reference",
                    "display"
                ]
            }
        },
        "detail_type": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string",
                    "default": ""
                },
                "code": {"$ref": "#/definitions/code2_type"},
                "status": {
                    "type": "string",
                    "default": ""
                },
                "doNotPerform": {
                    "type": "boolean",
                    "default": false
                },
                "scheduledTiming": {"$ref": "#/definitions/scheduledTiming_type"},
                "performer": {"$ref": "#/definitions/performer_type"},
                "description": {
                    "type": "string",
                    "default": ""
                }
            }
        },
        "activity_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "reference": {"$ref": "#/definitions/assigner_type"},
                    "extension": {"$ref": "#/definitions/extension2_type"},
                    "detail": {"$ref": "#/definitions/detail_type"}
                }
            }
        }
    }
}

=== EmekaC/BlockMom/referral.json
{
  "resourceType": "Patient",
  "id": "BlockMoM",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n<p>A maternity health information for a pregnant woman.</p>\n<p>LMP is 1st July, 2020. The woman has plan to take prenatal Iron and Folic acid, scheduled first antenatal, and plan for the second antenatal, subsequent and delivery </p>\n     </div>"
  },
  "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://blockmom.com/CodeSystem/v1",
            "code": "active"
          }
        ]
      },
      "system": "urn:oid:1.3.12.246.576.315.1.6",
      "value": "Patient/94d9ae7112f9d8ecd81c2abbbfcdf810221f1db347acd3e2171f8bb4878bd155",
      "period": {
        "start": "2020-10-11"
      },
      "assigner": {
        "display": "Digitalcare Tech."
      }
    }
  ],
  "active": true,
  "name": [
    {
      "use": "official",
      "family": "Chukwu",
      "given": [
        "Ngozi",
        "Edidiong"
      ]
    },
    {
      "use": "usual",
      "given": [
        "Ngozi"
      ]
    },
    {
      "use": "maiden",
      "family": "Bassey",
      "given": [
        "Ngozi",
        "Edidiong"
      ],
      "period": {
        "end": "2030"
      }
    }
  ],
  "telecom": [
    {
      "use": "home"
    },
    {
      "system": "phone",
      "value": "(234) 803 333 4444",
      "use": "mobile",
      "rank": 1
    },
    {
      "system": "phone",
      "value": "(234) 802 341 3333",
      "use": "work",
      "rank": 2
    },
    {
      "system": "phone",
      "value": "(232) 2222 3354",
      "use": "old",
      "period": {
        "end": "2015"
      }
    }
  ],
  "gender": "female",
  "birthDate": "1984-10-29",
  "_birthDate": {
    "extension": [
      {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthTime",
        "valueDateTime": "1984-10-29T13:50:40-01:00"
      }
    ]
  },
  "deceasedBoolean": false,
  "address": [
    {
      "use": "home",
      "type": "both",
      "text": "12 New layout",
      "line": [
        "AI"
      ],
      "city": "Abakaliki",
      "district": "",
      "state": "Ebonyi",
      "postalCode": "",
      "period": {
        "start": "1984-10-29"
      }
    }
  ],
  "contained": [
    {
      "resourceType": "Condition",
      "id": "BlockMoM1",
      "clinicalStatus": {
        "coding": [
          {
            "system": "https://icd.who.int/browse10/2016/en#",
            "code": "active"
          }
        ]
      },
      "verificationStatus": {
        "coding": [
          {
            "system": "https://icd.who.int/browse10/2016/en#",
            "code": "confirmed"
          }
        ]
      },
      "code": {
        "text": "Prolonged second stage (of labour)",
        "value": "O63.1"
      },
      "subject": {
        "reference": "Patient/94d9ae7112f9d8ecd81c2abbbfcdf810221f1db347acd3e2171f8bb4878bd155",
        "display": "Ngozi Chukwu"
      }
    },
    {
      "resourceType": "Practitioner",
      "id": "NMCN018/57102bfcdf81878bd1512f9d894d9aeecd81c2abb347acd3e2171f8bb421f1db",
      "name": [
        {
          "family": "Midwife",
          "given": [
            "Ngozi"
          ]
        }
      ]
    }
  ],
  "activity": [
    {
      "reference": {
        "display": "Urgent referral to General hospital"
      }
    },
    {
      "extension": [
        {
          "valueUri": "http://blockmom.com/fhir/careplan/1andetails"
        }
      ],
      "detail": {
        "kind": "Encounter",
        "code": {
          "coding": [
            {
              "system": "http://blockmom.com/mySystem",
              "code": "1an"
            }
          ],
          "text": "First Antenatal encounter"
        },
        "status": "active",
        "doNotPerform": false,
        "scheduledTiming": {
          "repeat": {
            "boundsPeriod": {
              "start": "2019-06-15",
              "end": "2019-06-16"
            }
          }
        },
        "performer": [
          {
            "reference": "NMCN018/57102bfcdf81878bd1512f9d894d9aeecd81c2abb347acd3e2171f8bb421f1db",
            "display": "Ngozi Midwife"
          }
        ],
        "description": "The first antenatal encounter. "
      }
    },
    {
      "detail": {
        "kind": "Appointment",
        "code": {
          "coding": [
            {
              "system": "http://blockmom.com/mySystem",
              "code": "an"
            }
          ],
          "text": "Follow-up Antenatal encounter"
        },
        "status": "scheduled",
        "doNotPerform": false,
        "scheduledTiming": {
          "repeat": {
            "boundsPeriod": {
              "start": "2019-07-17",
              "end": "2019-07-24"
            }
          }
        },
        "performer": [
          {
            "reference": "NMCN018/57102bfcdf81878bd1512f9d894d9aeecd81c2abb347acd3e2171f8bb421f1db",
            "display": "Ngozi Midwife"
          }
        ],
        "description": "The Second antenatal encounter has been scheduled. This is where a detailed physical examination is performed and the pregnanacy discussed with the mother-to-be."
      }
    }
  ]
}
